blank_issues_enabled: true
contact_links:
  - name: Questions and discussions
    url: https://github.com/Rm1n90/pitwall/discussions
    about: Please use discussions for open-ended questions, ideas, or general help if enabled for the repository.
